#!/bin/sh

domains=github.com

while [ "$#" -gt 0 ]; do
    case "$1" in
        --additional-github-domain)
            if [ "$#" -lt 2 ] || [ -z "$2" ]; then
                printf '%s\n' 'check-vcs-permalinks: --additional-github-domain requires a domain' >&2
                exit 2
            fi
            domains="$domains,$2"
            shift 2
            ;;
        --additional-github-domain=*)
            domain=${1#*=}
            if [ -z "$domain" ]; then
                printf '%s\n' 'check-vcs-permalinks: --additional-github-domain requires a domain' >&2
                exit 2
            fi
            domains="$domains,$domain"
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            break
            ;;
    esac
done

status=0

for filename
do
    if [ ! -f "$filename" ] || [ ! -r "$filename" ]; then
        printf '%s: cannot read file\n' "$filename" >&2
        status=1
        continue
    fi

    if awk -v filename="$filename" -v domains="$domains" '
        BEGIN {
            domain_count = split(domains, configured_domains, ",")
            for (i = 1; i <= domain_count; i++) {
                domain = configured_domains[i]
                gsub(/\./, "[.]", domain)
                patterns[i] = "https://" domain "/[^/[:space:]]+/[^/[:space:]]+/blob/[^/[:space:]]+/[^#[:space:]]+#L[0-9]+"
            }
        }
        {
            bad_line = 0
            for (i = 1; i <= domain_count; i++) {
                remaining = $0
                while (match(remaining, patterns[i])) {
                    link = substr(remaining, RSTART, RLENGTH)
                    split(link, fields, "/")
                    ref = fields[7]
                    if (length(ref) < 4 || length(ref) > 64 || ref ~ /[^0-9A-Fa-f]/) {
                        bad_line = 1
                        found = 1
                    }
                    remaining = substr(remaining, RSTART + RLENGTH)
                }
            }
            if (bad_line) {
                printf "%s:%d:%s\n", filename, FNR, $0
            }
        }
        END {
            exit found ? 1 : 0
        }
    ' "$filename"; then
        :
    else
        status=1
    fi
done

if [ "$status" -ne 0 ]; then
    printf '\nNon-permanent github link detected.\n'
    printf 'On any page on github press [y] to load a permalink.\n'
fi

exit "$status"
